### ISSUE TITLE
ISO-2 AC ChargingStatusRes calls get_evse_max_current_limit() without required protocol arg

### ISSUE THREAD

**Issue by JakeMG-INL** [IdahoLabResearch/AcCCS#80]
## What's wrong

`app/secc/states/iso15118_2_states.py:2167` builds `ChargingStatusRes` with:

```python
evse_max_current=await evse_controller.get_evse_max_current_limit(),
```

but `SimEVSEController.get_evse_max_current_limit(self, protocol: Protocol)` requires a `protocol` argument (no default). Every DC call site (e.g. lines ~2515-2520) correctly passes `Protocol.ISO_15118_2`; this AC call site does not, so building `ChargingStatusRes` in the ISO-15118-2 **AC** charging flow raises `TypeError: get_evse_max_current_limit() missing 1 required positional argument: 'protocol'`.

## Why it's latent

The signature has required `protocol` since commit `6401f85`; the emulator has no ISO-2 AC scenario in automated tests or the virtual demo, so the crash is dormant. Surfaced during the cross-file trace while auditing #73 — **not introduced by #73** (that change only touched the DIN branches).

## Fix

Pass `Protocol.ISO_15118_2` at the call site (matching the DC sites). Add an ISO-2 AC ChargingStatusRes build test to guard it.

## Found during

Audit of #73.

**Comment by JakeMG-INL** [comment]
## Implementation summary (agent, 2026-07-01)

**Branch / base:** development @ 9d8e2bd
**Files touched:**
  - `app/secc/states/iso15118_2_states.py` — pass `protocol=Protocol.ISO_15118_2` to `get_evse_max_current_limit()` at the ISO-2 AC `ChargingStatusRes` build site (line ~2167), matching the DC sites.
**Tests added:**
  - `tests/conformance/state_machine/secc/test_iso2_ac_charging_status.py::test_iso2_ac_charging_status_builds_response` — drives the real `ChargingStatus` state through the ADR-0003 `process_message()` seam with the controller in AC mode and asserts a `ChargingStatusRes(OK)` with a `PVEVSEMaxCurrent` builds without the missing-`protocol` `TypeError`.
**Verify:** PASS — new test is red without the fix (reproduces the exact `TypeError: get_evse_max_current_limit() missing 1 required positional argument: 'protocol'`) and green with it; full `tests/conformance/state_machine/` suite 51 passed. No ISO-2 AC virtual-demo scenario exists, so this state-machine-seam test is the finest runnable verification for the path (it builds a real `ChargingStatusRes` through the real EXI codec via `create_next_message`).
**Decisions made:**
  - Set `current_type = CurrentType.AC` directly in the test fixture — the CPD state normally sets it, but the test enters at `ChargingStatus`; this exercises the AC branch of `get_evse_max_current_limit` (returns `PVEVSEMaxCurrent`).
**Open caveats:** none

**Comment by JakeMG-INL** [comment]
Landed in c084f98 on development.

Pass Protocol.ISO_15118_2 to get_evse_max_current_limit() at the ISO-2 AC ChargingStatusRes build site, fixing the dormant missing-'protocol' TypeError, plus a state-machine-seam regression test.

Manual verification: confirmed the new test reproduces the exact TypeError with the fix reverted (red) and builds a ChargingStatusRes(OK) with it applied (green), and the full state_machine suite stays at 51 passed.
